import React from "react";
import { motion } from "motion/react";
import { Check, ExternalLink, Award, FileSpreadsheet } from "lucide-react";
import { Problem } from "../types";

interface ProblemCardProps {
  key?: string;
  problem: Problem;
  onToggleProgress: (leetcodeNum: string, isCompleted: boolean) => void;
  onSelect: (problem: Problem) => void;
}

export default function ProblemCard({ problem, onToggleProgress, onSelect }: ProblemCardProps): React.JSX.Element {
  const { leetcode_number, title, description, difficulty, category, isCustom, is_completed } = problem;

  // Generate perfect LeetCode url slug
  // e.g. "Contains Duplicate" -> "contains-duplicate"
  const slug = title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "") // remove special chars
    .replace(/\s+/g, "-")         // replace spaces with hyphens
    .replace(/-+/g, "-");         // replace double hyphens

  const isNumeric = /^\d+$/.test(leetcode_number);
  // Detect if title is a simple autogenerated placeholder like "LeetCode #123"
  const isDefaultTitle = title.toLowerCase().trim() === `leetcode #${leetcode_number}`.toLowerCase().trim() ||
                        title.toLowerCase().trim() === `leetcode #${leetcode_number.trim()}`.toLowerCase().trim() ||
                        title.toLowerCase().includes("leetcode #" + leetcode_number);

  const externalLink = isNumeric && !isDefaultTitle
    ? `https://leetcode.com/problems/${slug}/`
    : `https://www.google.com/search?q=LeetCode+${encodeURIComponent(leetcode_number)}${isDefaultTitle ? "" : `+${encodeURIComponent(title)}`}`;

  const diffColors = {
    Easy: {
      text: "text-emerald-400 bg-emerald-500/5 border-emerald-500/20",
      checkbox: "border-neutral-800 hover:border-emerald-500 checked:bg-emerald-500",
      accent: "bg-emerald-500",
    },
    Medium: {
      text: "text-amber-400 bg-amber-500/5 border-amber-500/20",
      checkbox: "border-neutral-800 hover:border-amber-500 checked:bg-amber-500",
      accent: "bg-amber-500",
    },
    Hard: {
      text: "text-rose-400 bg-rose-500/5 border-rose-500/20",
      checkbox: "border-neutral-800 hover:border-rose-500 checked:bg-rose-500",
      accent: "bg-rose-500",
    },
  };

  const activeTheme = diffColors[difficulty] || diffColors.Medium;
  return (
    <motion.div
      layout
      onClick={() => onSelect(problem)}
      className={`relative flex items-center gap-4 p-4 rounded-xl border transition-all duration-300 cursor-pointer select-none ${
        is_completed
          ? "bg-[#111317]/50 border-neutral-900/60 opacity-75"
          : "bg-neutral-900/40 hover:bg-[#14151a] border-neutral-800/80 hover:border-neutral-700/80 shadow-sm"
      }`}
      id={`problem-row-${leetcode_number}`}
    >
      {/* Handcrafted Checkbox Slider */}
      <button
        onClick={(e) => {
          e.stopPropagation();
          onToggleProgress(leetcode_number, !is_completed);
        }}
        className={`w-5 h-5 rounded-md border flex items-center justify-center shrink-0 transition-all cursor-pointer ${
          is_completed
            ? "bg-emerald-500 border-emerald-500 shadow-[0_0_10px_rgba(16,185,129,0.3)] text-neutral-950"
            : "border-neutral-700 hover:border-emerald-500 bg-neutral-950 text-transparent"
        }`}
        title={is_completed ? "Mark incomplete" : "Mark complete"}
      >
        <Check className="w-3.5 h-3.5 stroke-[3]" />
      </button>

      {/* LeetCode number ID */}
      <div className="text-left font-mono font-semibold text-xs text-neutral-500 w-12 shrink-0">
        #{leetcode_number}
      </div>

      {/* Content details */}
      <div className="flex-grow min-w-0 pr-2">
        <div className="flex items-center gap-2 mb-1">
          <h4
            className={`font-semibold text-sm truncate tracking-tight transition-all ${
              is_completed ? "line-through text-neutral-500" : "text-neutral-200"
            }`}
          >
            {title}
          </h4>

          {isCustom && (
            <span className="text-[9px] font-bold px-1.5 py-0.5 rounded border bg-violet-500/10 border-violet-500/30 text-violet-400 uppercase tracking-widest font-mono shrink-0">
              Custom
            </span>
          )}
        </div>
        <p className="text-xs text-neutral-400 leading-normal truncate-2-lines font-sans">
          {description}
        </p>
      </div>

      {/* Badges/Category and Actions container */}
      <div className="flex items-center gap-3 shrink-0">
        {/* Category ID (only visible on md space) */}
        <span className="hidden sm:inline-flex text-[10px] font-mono text-neutral-500 bg-neutral-950 px-2.5 py-1 rounded-md border border-neutral-900 leading-none">
          {category}
        </span>

        {/* Difficulty badge */}
        <span
          className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border tracking-wide font-mono ${activeTheme.text}`}
        >
          {difficulty}
        </span>

        {/* Challenge Link */}
        <a
          href={externalLink}
          target="_blank"
          rel="noreferrer"
          onClick={(e) => e.stopPropagation()}
          className="p-1.5 rounded-lg bg-neutral-950 text-neutral-500 hover:text-emerald-400 border border-neutral-900 hover:border-neutral-800 transition-colors"
          title="Open Problem on LeetCode"
          id={`problem-link-${leetcode_number}`}
        >
          <ExternalLink className="w-3.5 h-3.5" />
        </a>
      </div>
    </motion.div>
  );
}
